### PR TITLE
Updated nbd dispatch error handling around fatal errors in async r/w

### PR DESCRIPTION
**Pull request by jimmyaxod**
This removes a potential block, if dispatch workers cannot write responses to the nbd socket.

Firstly, now any fatal errors in async r/w operations are written to the fatal channel non-blocking with a select{}
Secondly, the Handle() now checks the channel at the start of each loop, and returns if there was an error.

It should be noted that currently, the error from Handle() is discarded in ExposedStorageNBDNL. This should be fixed and routed to the consumer of ExposedStorageNBDNL in some way to say that a critical error happened in the nbd subsystem.

### CODE REVIEW

**Review by lgfa29 — APPROVED** [review]
I haven't had a chance to test this yet, but LGTM!

Just noting that the non-block channel write may drop errors, but that seems fine (and somewhat expected) since the only scenarios this would happen would be if nobody is listening on `fatal` (so there's nowhere to report the error) or if there's already an error waiting in the channel (which will cause `Handle()` to exit).

**Comment by jimmyaxod** [comment]
> I haven't had a chance to test this yet, but LGTM!
> 
> Just noting that the non-block channel write may drop errors, but that seems fine (and somewhat expected) since the only scenarios this would happen would be if nobody is listening on `fatal` (so there's nowhere to report the error) or if there's already an error waiting in the channel (which will cause `Handle()` to exit).

Correct... The fatal channel is of size 1, so can hold one fatal error. We do not care about any further fatal errors, as we only need to return from Handle() once.

**Comment by pojntfx** [comment]
@jimmyaxod One thing I'm wondering about with the non-blocking channels - what if there are multiple fatal errors that we do actually care about? The use case I'm thinking about here is mostly context cancellations, where `ctx.Err()` is set by the cancel cause, and that specific error has to bubble up (so that we can distinguish between a context cancellation that's internal to Silo - like a write to a Silo peer timing out - and a context cancellation that we have intentionally triggered, such as by sending an interrupt signal). In Drafter, we collect all of these errors with `errors.Join` instead of dropping them for this reason, but it might also not apply to how Silo is handling it

**Comment by jimmyaxod** [comment]
> @jimmyaxod One thing I'm wondering about with the non-blocking channels - what if there are multiple fatal errors that we do actually care about? The use case I'm thinking about here is mostly context cancellations, where `ctx.Err()` is set by the cancel cause, and that specific error has to bubble up (so that we can distinguish between a context cancellation that's internal to Silo - like a write to a Silo peer timing out - and a context cancellation that we have intentionally triggered, such as by sending an interrupt signal). In Drafter, we collect all of these errors with `errors.Join` instead of dropping them for this reason, but it might also not apply to how Silo is handling it

I see your point, but in this case, the only fatal error in this channel occurs from "I cannot write a response to the nbd fd" (from writeResponse in an async read/write). We may have multiple of these if we have multiple fds on the nbd device, but I'd say we don't care if more than one cannot be written to... it's going to be critical in any event.

A context cancel is still handled within the main Handle() loop, not in the individual fd handler goroutines or individual read/write goroutines.

So the errors from the Handle() will be:
 * context.Cancelled
 * a critical error from ONE of the nbd fd handler goroutines if a writeResponse to the fd failed.
 * something else eg error reading from nbd fd, or something unsupported.

**Comment by jimmyaxod** [comment]
Rolled into jm/improvements

**Pull request closed without merging**
